# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'departurewindow(ids).ui'
#
# Created: Mon Mar 02 03:13:20 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(812, 390)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.departuresTab = QtGui.QWidget()
        self.departuresTab.setObjectName(_fromUtf8("departuresTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.departuresTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.depInfoBox = QtGui.QGroupBox(self.departuresTab)
        self.depInfoBox.setObjectName(_fromUtf8("depInfoBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.depInfoBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.flowLabel = QtGui.QLabel(self.depInfoBox)
        self.flowLabel.setObjectName(_fromUtf8("flowLabel"))
        self.gridLayout_6.addWidget(self.flowLabel, 0, 2, 1, 1)
        self.nameLabel = QtGui.QLabel(self.depInfoBox)
        self.nameLabel.setObjectName(_fromUtf8("nameLabel"))
        self.gridLayout_6.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.departureNameBrowser = QtGui.QLineEdit(self.depInfoBox)
        self.departureNameBrowser.setAutoFillBackground(False)
        self.departureNameBrowser.setReadOnly(True)
        self.departureNameBrowser.setObjectName(_fromUtf8("departureNameBrowser"))
        self.gridLayout_6.addWidget(self.departureNameBrowser, 0, 1, 1, 1)
        self.departureFlowBrowser = QtGui.QLineEdit(self.depInfoBox)
        self.departureFlowBrowser.setReadOnly(True)
        self.departureFlowBrowser.setObjectName(_fromUtf8("departureFlowBrowser"))
        self.gridLayout_6.addWidget(self.departureFlowBrowser, 0, 3, 1, 1)
        self.departureHeadingBrowser = QtGui.QLineEdit(self.depInfoBox)
        self.departureHeadingBrowser.setReadOnly(True)
        self.departureHeadingBrowser.setObjectName(_fromUtf8("departureHeadingBrowser"))
        self.gridLayout_6.addWidget(self.departureHeadingBrowser, 1, 1, 1, 1)
        self.correspondingDepLabel = QtGui.QLabel(self.depInfoBox)
        self.correspondingDepLabel.setObjectName(_fromUtf8("correspondingDepLabel"))
        self.gridLayout_6.addWidget(self.correspondingDepLabel, 1, 2, 1, 1)
        self.correspondingDepartureBrowser = QtGui.QLineEdit(self.depInfoBox)
        self.correspondingDepartureBrowser.setReadOnly(True)
        self.correspondingDepartureBrowser.setObjectName(_fromUtf8("correspondingDepartureBrowser"))
        self.gridLayout_6.addWidget(self.correspondingDepartureBrowser, 1, 3, 1, 1)
        self.trasnitionsLabel = QtGui.QLabel(self.depInfoBox)
        self.trasnitionsLabel.setObjectName(_fromUtf8("trasnitionsLabel"))
        self.gridLayout_6.addWidget(self.trasnitionsLabel, 3, 0, 1, 1)
        self.firstFixLabe = QtGui.QLabel(self.depInfoBox)
        self.firstFixLabe.setObjectName(_fromUtf8("firstFixLabe"))
        self.gridLayout_6.addWidget(self.firstFixLabe, 2, 0, 1, 1)
        self.headingLabel = QtGui.QLabel(self.depInfoBox)
        self.headingLabel.setObjectName(_fromUtf8("headingLabel"))
        self.gridLayout_6.addWidget(self.headingLabel, 1, 0, 1, 1)
        self.departureTransitionsBrowser = QtGui.QLineEdit(self.depInfoBox)
        self.departureTransitionsBrowser.setReadOnly(True)
        self.departureTransitionsBrowser.setObjectName(_fromUtf8("departureTransitionsBrowser"))
        self.gridLayout_6.addWidget(self.departureTransitionsBrowser, 3, 1, 1, 3)
        self.departureFirstFixBrowser = QtGui.QLineEdit(self.depInfoBox)
        self.departureFirstFixBrowser.setReadOnly(True)
        self.departureFirstFixBrowser.setObjectName(_fromUtf8("departureFirstFixBrowser"))
        self.gridLayout_6.addWidget(self.departureFirstFixBrowser, 2, 1, 1, 3)
        self.gridLayout_3.addWidget(self.depInfoBox, 0, 1, 2, 1)
        self.runwayBox = QtGui.QGroupBox(self.departuresTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runwayBox.sizePolicy().hasHeightForWidth())
        self.runwayBox.setSizePolicy(sizePolicy)
        self.runwayBox.setObjectName(_fromUtf8("runwayBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.runwayBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.runwayComboBox = QtGui.QComboBox(self.runwayBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runwayComboBox.sizePolicy().hasHeightForWidth())
        self.runwayComboBox.setSizePolicy(sizePolicy)
        self.runwayComboBox.setObjectName(_fromUtf8("runwayComboBox"))
        self.gridLayout_4.addWidget(self.runwayComboBox, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.runwayBox, 0, 0, 1, 1)
        self.departureBox = QtGui.QGroupBox(self.departuresTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departureBox.sizePolicy().hasHeightForWidth())
        self.departureBox.setSizePolicy(sizePolicy)
        self.departureBox.setObjectName(_fromUtf8("departureBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.departureBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.departureComboBox = QtGui.QComboBox(self.departureBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departureComboBox.sizePolicy().hasHeightForWidth())
        self.departureComboBox.setSizePolicy(sizePolicy)
        self.departureComboBox.setObjectName(_fromUtf8("departureComboBox"))
        self.gridLayout_5.addWidget(self.departureComboBox, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.departureBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.departuresTab, _fromUtf8(""))
        self.approachesTab = QtGui.QWidget()
        self.approachesTab.setObjectName(_fromUtf8("approachesTab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.approachesTab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.approachFlowBox = QtGui.QGroupBox(self.approachesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.approachFlowBox.sizePolicy().hasHeightForWidth())
        self.approachFlowBox.setSizePolicy(sizePolicy)
        self.approachFlowBox.setObjectName(_fromUtf8("approachFlowBox"))
        self.gridLayout_12 = QtGui.QGridLayout(self.approachFlowBox)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.approachFlowComboBox = QtGui.QComboBox(self.approachFlowBox)
        self.approachFlowComboBox.setMinimumSize(QtCore.QSize(85, 0))
        self.approachFlowComboBox.setObjectName(_fromUtf8("approachFlowComboBox"))
        self.gridLayout_12.addWidget(self.approachFlowComboBox, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.approachFlowBox, 0, 0, 1, 1)
        self.approachInfoBox = QtGui.QGroupBox(self.approachesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.approachInfoBox.sizePolicy().hasHeightForWidth())
        self.approachInfoBox.setSizePolicy(sizePolicy)
        self.approachInfoBox.setObjectName(_fromUtf8("approachInfoBox"))
        self.gridLayout_13 = QtGui.QGridLayout(self.approachInfoBox)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.approachPictureLabel = QtGui.QLabel(self.approachInfoBox)
        self.approachPictureLabel.setText(_fromUtf8(""))
        self.approachPictureLabel.setObjectName(_fromUtf8("approachPictureLabel"))
        self.gridLayout_13.addWidget(self.approachPictureLabel, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.approachInfoBox, 0, 1, 1, 1)
        self.tabWidget.addTab(self.approachesTab, _fromUtf8(""))
        self.IDS = QtGui.QWidget()
        self.IDS.setObjectName(_fromUtf8("IDS"))
        self.gridLayout_14 = QtGui.QGridLayout(self.IDS)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.idAirportBox = QtGui.QGroupBox(self.IDS)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idAirportBox.sizePolicy().hasHeightForWidth())
        self.idAirportBox.setSizePolicy(sizePolicy)
        self.idAirportBox.setObjectName(_fromUtf8("idAirportBox"))
        self.gridLayout_18 = QtGui.QGridLayout(self.idAirportBox)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.idAirportList = QtGui.QComboBox(self.idAirportBox)
        self.idAirportList.setObjectName(_fromUtf8("idAirportList"))
        self.gridLayout_18.addWidget(self.idAirportList, 0, 1, 1, 1)
        self.gridLayout_14.addWidget(self.idAirportBox, 1, 0, 2, 1)
        self.idPirepsGroupBox = QtGui.QGroupBox(self.IDS)
        self.idPirepsGroupBox.setObjectName(_fromUtf8("idPirepsGroupBox"))
        self.gridLayout_20 = QtGui.QGridLayout(self.idPirepsGroupBox)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.gridLayout_14.addWidget(self.idPirepsGroupBox, 2, 1, 1, 1)
        self.idAtisGroupBox = QtGui.QGroupBox(self.IDS)
        self.idAtisGroupBox.setObjectName(_fromUtf8("idAtisGroupBox"))
        self.gridLayout_19 = QtGui.QGridLayout(self.idAtisGroupBox)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.idAtisWxLabel = QtGui.QLabel(self.idAtisGroupBox)
        self.idAtisWxLabel.setObjectName(_fromUtf8("idAtisWxLabel"))
        self.gridLayout_19.addWidget(self.idAtisWxLabel, 2, 2, 1, 1)
        self.idAtisCodeEdit = QtGui.QLineEdit(self.idAtisGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.idAtisCodeEdit.sizePolicy().hasHeightForWidth())
        self.idAtisCodeEdit.setSizePolicy(sizePolicy)
        self.idAtisCodeEdit.setMaximumSize(QtCore.QSize(38, 16777215))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.idAtisCodeEdit.setFont(font)
        self.idAtisCodeEdit.setText(_fromUtf8(""))
        self.idAtisCodeEdit.setMaxLength(1)
        self.idAtisCodeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.idAtisCodeEdit.setObjectName(_fromUtf8("idAtisCodeEdit"))
        self.gridLayout_19.addWidget(self.idAtisCodeEdit, 2, 1, 1, 1)
        self.idAtisCodeLabel = QtGui.QLabel(self.idAtisGroupBox)
        self.idAtisCodeLabel.setObjectName(_fromUtf8("idAtisCodeLabel"))
        self.gridLayout_19.addWidget(self.idAtisCodeLabel, 2, 0, 1, 1)
        self.idWxBrowser = QtGui.QLineEdit(self.idAtisGroupBox)
        self.idWxBrowser.setReadOnly(True)
        self.idWxBrowser.setObjectName(_fromUtf8("idWxBrowser"))
        self.gridLayout_19.addWidget(self.idWxBrowser, 2, 3, 1, 1)
        self.gridLayout_14.addWidget(self.idAtisGroupBox, 1, 1, 1, 1)
        self.tabWidget.addTab(self.IDS, _fromUtf8(""))
        self.arrivalsTab = QtGui.QWidget()
        self.arrivalsTab.setObjectName(_fromUtf8("arrivalsTab"))
        self.gridLayout_7 = QtGui.QGridLayout(self.arrivalsTab)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.arrivalInformationBox = QtGui.QGroupBox(self.arrivalsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrivalInformationBox.sizePolicy().hasHeightForWidth())
        self.arrivalInformationBox.setSizePolicy(sizePolicy)
        self.arrivalInformationBox.setObjectName(_fromUtf8("arrivalInformationBox"))
        self.gridLayout_10 = QtGui.QGridLayout(self.arrivalInformationBox)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.arrivalsCrossLabel = QtGui.QLabel(self.arrivalInformationBox)
        self.arrivalsCrossLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.arrivalsCrossLabel.setObjectName(_fromUtf8("arrivalsCrossLabel"))
        self.gridLayout_10.addWidget(self.arrivalsCrossLabel, 1, 0, 1, 1)
        self.arrivalsNameLabel = QtGui.QLabel(self.arrivalInformationBox)
        self.arrivalsNameLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.arrivalsNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.arrivalsNameLabel.setWordWrap(False)
        self.arrivalsNameLabel.setOpenExternalLinks(False)
        self.arrivalsNameLabel.setObjectName(_fromUtf8("arrivalsNameLabel"))
        self.gridLayout_10.addWidget(self.arrivalsNameLabel, 0, 0, 1, 1)
        self.arrivalsCorrespondingLabel = QtGui.QLabel(self.arrivalInformationBox)
        self.arrivalsCorrespondingLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.arrivalsCorrespondingLabel.setObjectName(_fromUtf8("arrivalsCorrespondingLabel"))
        self.gridLayout_10.addWidget(self.arrivalsCorrespondingLabel, 2, 0, 1, 1)
        self.arrivalNameBrowser = QtGui.QLineEdit(self.arrivalInformationBox)
        self.arrivalNameBrowser.setObjectName(_fromUtf8("arrivalNameBrowser"))
        self.gridLayout_10.addWidget(self.arrivalNameBrowser, 0, 1, 1, 1)
        self.arrivalCrossBrowser = QtGui.QLineEdit(self.arrivalInformationBox)
        self.arrivalCrossBrowser.setObjectName(_fromUtf8("arrivalCrossBrowser"))
        self.gridLayout_10.addWidget(self.arrivalCrossBrowser, 1, 1, 1, 1)
        self.correspondingArrivalBrowser = QtGui.QLineEdit(self.arrivalInformationBox)
        self.correspondingArrivalBrowser.setObjectName(_fromUtf8("correspondingArrivalBrowser"))
        self.gridLayout_10.addWidget(self.correspondingArrivalBrowser, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.arrivalInformationBox, 1, 3, 2, 1)
        self.arrivalProcedureBox = QtGui.QGroupBox(self.arrivalsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrivalProcedureBox.sizePolicy().hasHeightForWidth())
        self.arrivalProcedureBox.setSizePolicy(sizePolicy)
        self.arrivalProcedureBox.setObjectName(_fromUtf8("arrivalProcedureBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.arrivalProcedureBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.arrivalProcedureComboBox = QtGui.QComboBox(self.arrivalProcedureBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrivalProcedureComboBox.sizePolicy().hasHeightForWidth())
        self.arrivalProcedureComboBox.setSizePolicy(sizePolicy)
        self.arrivalProcedureComboBox.setObjectName(_fromUtf8("arrivalProcedureComboBox"))
        self.gridLayout_9.addWidget(self.arrivalProcedureComboBox, 1, 0, 1, 1)
        self.gridLayout_7.addWidget(self.arrivalProcedureBox, 2, 0, 1, 3)
        self.arrivalFlowBox = QtGui.QGroupBox(self.arrivalsTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrivalFlowBox.sizePolicy().hasHeightForWidth())
        self.arrivalFlowBox.setSizePolicy(sizePolicy)
        self.arrivalFlowBox.setObjectName(_fromUtf8("arrivalFlowBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.arrivalFlowBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.arrivalFlowComboBox = QtGui.QComboBox(self.arrivalFlowBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrivalFlowComboBox.sizePolicy().hasHeightForWidth())
        self.arrivalFlowComboBox.setSizePolicy(sizePolicy)
        self.arrivalFlowComboBox.setObjectName(_fromUtf8("arrivalFlowComboBox"))
        self.gridLayout_8.addWidget(self.arrivalFlowComboBox, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.arrivalFlowBox, 1, 0, 1, 3)
        self.tabWidget.addTab(self.arrivalsTab, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_16.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.gridLayout_15.addWidget(self.groupBox_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 1, 1, 1)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.exitButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.gridLayout_2.addWidget(self.exitButton, 0, 1, 1, 1)
        self.stayOnTopButton = QtGui.QRadioButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stayOnTopButton.sizePolicy().hasHeightForWidth())
        self.stayOnTopButton.setSizePolicy(sizePolicy)
        self.stayOnTopButton.setObjectName(_fromUtf8("stayOnTopButton"))
        self.gridLayout_2.addWidget(self.stayOnTopButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Departure Info", None))
        self.depInfoBox.setTitle(_translate("MainWindow", "Departure Information", None))
        self.flowLabel.setText(_translate("MainWindow", "Flow:", None))
        self.nameLabel.setText(_translate("MainWindow", "Name:", None))
        self.correspondingDepLabel.setText(_translate("MainWindow", "Corresponding Depature:", None))
        self.trasnitionsLabel.setText(_translate("MainWindow", "Transitions:", None))
        self.firstFixLabe.setText(_translate("MainWindow", "First FIX:", None))
        self.headingLabel.setText(_translate("MainWindow", "Heading:", None))
        self.runwayBox.setTitle(_translate("MainWindow", "Departure Runway", None))
        self.departureBox.setTitle(_translate("MainWindow", "Departure Procedure", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.departuresTab), _translate("MainWindow", "Departures", None))
        self.approachFlowBox.setTitle(_translate("MainWindow", "Flow", None))
        self.approachInfoBox.setTitle(_translate("MainWindow", "Approach Information", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.approachesTab), _translate("MainWindow", "Approaches", None))
        self.idAirportBox.setTitle(_translate("MainWindow", "Airport", None))
        self.idPirepsGroupBox.setTitle(_translate("MainWindow", "PIREPS", None))
        self.idAtisGroupBox.setTitle(_translate("MainWindow", "ATIS", None))
        self.idAtisWxLabel.setText(_translate("MainWindow", "Wx Info:", None))
        self.idAtisCodeLabel.setText(_translate("MainWindow", "Code:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.IDS), _translate("MainWindow", "Information Display 1", None))
        self.arrivalInformationBox.setTitle(_translate("MainWindow", "Arrival Information", None))
        self.arrivalsCrossLabel.setText(_translate("MainWindow", "Crossing Restriction:", None))
        self.arrivalsNameLabel.setText(_translate("MainWindow", "Name:", None))
        self.arrivalsCorrespondingLabel.setText(_translate("MainWindow", "Corresponding Arrival:", None))
        self.arrivalProcedureBox.setTitle(_translate("MainWindow", "Arrival Procedure", None))
        self.arrivalFlowBox.setTitle(_translate("MainWindow", "Flow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.arrivalsTab), _translate("MainWindow", "ComingSoon! Arrivals", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Enter Callsign", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Information", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Coming Soon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Just Another Tab", None))
        self.exitButton.setText(_translate("MainWindow", "Exit", None))
        self.stayOnTopButton.setText(_translate("MainWindow", "Stay on Top", None))

